artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL_label: https://storage.googleapis.com/openimages/open_images_extended_miap/open_images_extended_miap_boxes_val.csv
  local_data_file: artifacts/data_ingestion/image
  source_URL_for_image: https://storage.googleapis.com/openimages/open_images_extended_miap/open_images_extended_miap_images_val.lst
  source_code_download: https://raw.githubusercontent.com/openimages/dataset/master/downloader.py

data_validation_and_preprocess:
  root_dir: artifacts/data_validation/
  label_root_data: artifacts/data_ingestion/label_root.csv
  label_process_data: artifacts/data_validation/label.csv
  image_root_data: artifacts/data_ingestion/image/
  image_process_data: artifacts/data_validation/image/
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  label_process_data: artifacts/data_validation/label.csv
  image_train_data: artifacts/data_transformation/train/
  image_test_data: artifacts/data_transformation/test/
  image_root_data: artifacts/data_validation/image/


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

